# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: docker login 
      env:
       DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
       DOCKER_PASSWOD: ${{secrets.DOCKER_PASSWORD}}       
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWOD   
    - name: docker build 
      run: |      
         docker build -t shijukuchelan/helloworld:1 .
    - name: docker push 
      run: |
       docker push shijukuchelan/helloworld:1
